### ISSUE TITLE
Traversal projects should be skipped

### ISSUE THREAD

**Issue by dfederm** [jeffkl/SlnGen#30]
Traversal-style projects (dirs.proj) should be skipped (and perhaps traversed?) but not actually added to the sln.

**Comment by jeffkl** [comment]
We have logic to skip projects [here](https://github.com/jeffkl/SlnGen/blob/master/src/SlnGen.Build.Tasks/SlnGen.cs#L99).  You can set `IncludeInSolutionFile` to `false` for any generic project.  For traversal projects, you must set `IsTraversal` to `true`.  This may or may not be set for you depending on what you're using.  It is set in CBT but probably not CoreXT.  We didn't want to filter based on the file name because we wanted it to be more explicit.  So the consumer must set the property.
